# Generated by Django 5.0 on 2024-01-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_pusblished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pusblished',
            new_name='published',
        ),
    ]
